### ISSUE TITLE
How to use Vulcan API in Vulcan-next-starter ?

### ISSUE THREAD

**Issue by adalidda** [VulcanJS/vulcan-next-starter#54]
Hi,

The doc of vulcan say:

Connecting Remotely
You might sometimes need to connect to your GraphQL endpoint (typically accessible at http://yourapp.com/graphql) from outside your app.

API Key
You can make authorized requests to your GraphQL endpoint by defining an arbitrary vulcan.apiKey setting in your settings.json file (make sure to keep it private by keeping it out of the public block), and then including an apikey header whose value matches that API key:

{
  "vulcan": {
    "apiKey": "123foo"
  }
}

How do we use vulcan api in vulcan-next-starter ?

Thank You
Adalidda

**Comment by eric-burel** [comment]
Hi!  

- `apiKey` is meant for server to server communication, because it has to stay private. You won't need it here, except in API routes.

- For VNS to Vulcan, so client to server communication, you'll want to setup CORS instead. You can check [Vulcan's sample settings](https://github.com/VulcanJS/Vulcan/blob/devel/sample_settings.json). 

As a default, you'll have "guests" access, but we have introduced endpoints so that you can log in from the Next app and get the right token. However at this point, you'll have to develop this auth system on your own, we haven't yet have time to provide hooks or even an UI to do so, sorry.
